export const WHITE = '#ffffff';
const BLACK = '#151515';

export const CARDS = [
  { id: 1, type: 1, text: 'Red', color: '#dd2b2b', subText: 'Tomato' },
  { id: 2, type: 1, text: 'Red', color: '#dd2b2b', subText: 'Blood' },
  { id: 3, type: 1, text: 'Red', color: '#dd2b2b', subText: 'Deadpool' },
  { id: 4, type: 1, text: 'Red', color: '#dd2b2b', subText: 'Ladybug' },
  { id: 5, type: 2, text: 'Blue', color: '#1aa0ff', subText: 'Sea' },
  { id: 6, type: 2, text: 'Blue', color: '#1aa0ff', subText: 'Blueberry' },
  { id: 7, type: 2, text: 'Blue', color: '#1aa0ff', subText: 'Sky' },
  { id: 8, type: 2, text: 'Blue', color: '#1aa0ff', subText: 'Smurf' },
  { id: 9, type: 3, text: 'Green', color: '#33b743', subText: 'Grinch' },
  { id: 10, type: 3, text: 'Green', color: '#33b743', subText: 'Spinach' },
  { id: 11, type: 3, text: 'Green', color: '#33b743', subText: 'Moss' },
  { id: 12, type: 3, text: 'Green', color: '#33b743', subText: 'Grasshopper' },
  {
    id: 13,
    type: 4,
    text: 'Yellow',
    color: '#ffff61',
    subText: 'Duck',
    textColor: BLACK,
  },
  {
    id: 14,
    type: 4,
    text: 'Yellow',
    color: '#ffff61',
    subText: 'Banana',
    textColor: BLACK,
  },
  {
    id: 15,
    type: 4,
    text: 'Yellow',
    color: '#ffff61',
    subText: 'Lemon',
    textColor: BLACK,
  },
  {
    id: 16,
    type: 4,
    text: 'Yellow',
    color: '#ffff61',
    subText: 'Pikachu',
    textColor: BLACK,
  },
  { id: 17, type: 5, text: 'Orange', color: '#ffab37', subText: 'Orange' },
  { id: 18, type: 5, text: 'Orange', color: '#ffab37', subText: 'Fox' },
  { id: 19, type: 5, text: 'Orange', color: '#ffab37', subText: 'Pumkin' },
  { id: 20, type: 5, text: 'Orange', color: '#ffab37', subText: 'Garfield' },
  {
    id: 21,
    type: 6,
    text: 'Pink',
    color: '#ffb3c0',
    subText: 'Cotton candy',
    textColor: BLACK,
  },
  {
    id: 22,
    type: 6,
    text: 'Pink',
    color: '#ffb3c0',
    subText: 'Pig',
    textColor: BLACK,
  },
  {
    id: 23,
    type: 6,
    text: 'Pink',
    color: '#ffb3c0',
    subText: 'Dragon fruit',
    textColor: BLACK,
  },
  {
    id: 24,
    type: 6,
    text: 'Pink',
    color: '#ffb3c0',
    subText: 'Kirby',
    textColor: BLACK,
  },
  { id: 25, type: 7, text: 'Brown', color: '#b76933', subText: 'Soil' },
  { id: 26, type: 7, text: 'Brown', color: '#b76933', subText: 'Bear' },
  { id: 27, type: 7, text: 'Brown', color: '#b76933', subText: 'Jerry' },
  { id: 28, type: 7, text: 'Brown', color: '#b76933', subText: 'Chocolate' },
  { id: 29, type: 8, text: 'Gray', color: '#9e9e9e', subText: 'Bugs Bunny' },
  { id: 30, type: 8, text: 'Gray', color: '#9e9e9e', subText: 'Koala' },
  { id: 31, type: 8, text: 'Gray', color: '#9e9e9e', subText: 'Rocks' },
  { id: 32, type: 8, text: 'Gray', color: '#9e9e9e', subText: 'Moon' },
  { id: 33, type: 9, text: 'Purple', color: '#c82ec8', subText: 'Thanos' },
  { id: 34, type: 9, text: 'Purple', color: '#c82ec8', subText: 'Eggplant' },
  { id: 35, type: 9, text: 'Purple', color: '#c82ec8', subText: 'Grapes' },
  { id: 36, type: 9, text: 'Purple', color: '#c82ec8', subText: 'Lavender' },
  { id: 37, type: 10, text: 'Black', color: '#151515', subText: 'Batman' },
  { id: 38, type: 10, text: 'Black', color: '#151515', subText: 'Rat' },
  { id: 39, type: 10, text: 'Black', color: '#151515', subText: 'Ink' },
  { id: 40, type: 10, text: 'Black', color: '#151515', subText: 'Charcoal' },
];

export const STATUS_ACTION = 1;
export const STATUS_DRAW = 2;
export const STATUS_SELECT = 3;
export const STATUS_COLLECT = 4;
export const STATUS_NONE = 5;
